### ISSUE TITLE
No configure option for making pppd authenticates with RADIUS server use TCP ?

### ISSUE THREAD

**Issue by wumch** [wkz/pppd#1]
According to RFC6613 (2012), it's possible to communicate with RADIUS server use TCP, 
is there a configure option for picking UDP or TCP ?
I cannot find it in either ppp/\* or freeradiusclient.conf.

**Comment by Neustradamus** [comment]
@wumch: Please go to: https://github.com/paulusmack/ppp :)

**Comment by Neustradamus** [comment]
@wumch: Please go to: https://github.com/paulusmack/ppp :)

Maybe you can see for your changes:
- https://github.com/wumch/pppd

**Comment by Neustradamus** [comment]
@wumch: Have you done a PR with your changes in official PPP source code?
- https://github.com/ppp-project/ppp
